### ISSUE TITLE
Prepend dash to each note

### ISSUE THREAD

**Issue by AeliusSaionji** [Fertion/QuickMDCapture#2]
I was able to configure QuickMDCapture to use my yyyy-MM-dd.md daily note, and each new submission is appended to a newline in that file - nice!

However, Logseq is my tool of choice for managing the collection of md notes, and QuickMDCapture would play nicer with Logseq if each newline began with a bullet like so:
```md
- note 1
- note 2
```

thanks!

**Comment by Fertion** [comment]
Thank you for the idea. I've added it to the backlog and will implement this feature a bit later.

**Comment by TheGrandJaggard** [comment]
Please make this an option not hard-coded!

**Comment by Fertion** [comment]
Hi, added such a setting in the latest update https://github.com/Fertion/QuickMDCapture/releases/tag/1.2.0
