### ISSUE TITLE
Text in Note title format

### ISSUE THREAD

**Issue by TheGrandJaggard** [Fertion/QuickMDCapture#3]
May we please get the ability to put text in the "Note title format" field? I want something like "yyyy-MM-dd from QuickMDCapture". When I try to do this I get a generic error every time I try to save a note. 

This functionality may already exist. If it does, how do I insert plain text?
Thanks!

**Comment by Fertion** [comment]
Hi, I added this setting in the latest update https://github.com/Fertion/QuickMDCapture/releases/tag/1.2.0. In your case, you will need to specify the template in the following format: "{{yyyy-MM-dd}} from QuickMDCapture."

**Comment by TheGrandJaggard** [comment]
Thank you!
