### ISSUE TITLE
[FR] Allow Custom Date Formats for Creation Time in Frontmatter YAML

### ISSUE THREAD

**Issue by error451** [Fertion/QuickMDCapture#4]
When enabling the option to capture the creation time in the frontmatter YAML, the date format is currently hard-coded to `yyyy.MM.dd HH:mm:ss`.

**Proposed Enhancements:**
1. **ISO Format Option:** Introduce an option to use the ISO 8601 date format (`YYYY-MM-DDTHH:mm:ssZ`). This format is widely recognized and easier to implement.
2. **Custom Format Option:** Allow users to specify a custom date format, similar to the formatting available in the `Note Title Template`.

**Benefits:**
- **Flexibility:** Users can choose a date format that best fits their workflow or project requirements.
- **Compatibility:** Supporting ISO format enhances interoperability with other tools and systems that utilize standardized date formats.
- **Customization:** Offering custom formats allows for personalized setups, improving user experience.

**Comment by Fertion** [comment]
@error451  Hi, thanks for the idea. For some reason I thought I used the obsidian standard format. Now I realize that obsidian can handle my format, but by default it creates a different format. I will add the functionality in the next update one of these days.

**Comment by Fertion** [comment]
@error451  Hi, I added this setting in the latest update https://github.com/Fertion/QuickMDCapture/releases/tag/1.2.0.  
For the format you need, it should be {{YYYY-MM-DD}}T{{HH:mm:ssZ}}.  
Could you please let me know if this works as you need?

**Comment by error451** [comment]
Thank you, I will close the issue then, and I let you know if I notice something that doesn't work as expected
But currently I can't test it because i have the same crashing bug on MIUI 13 / android 12 https://github.com/Fertion/QuickMDCapture/issues/7 Is the patch code for that bug on github or is the pre-builded APK currently the only way to solve the problem?

**Comment by Fertion** [comment]
> Thank you, I will close the issue then, and I let you know if I notice something that doesn't work as expected
> But currently I can't test it because i have the same crashing bug on MIUI 13 / android 12 https://github.com/Fertion/QuickMDCapture/issues/7 Is the patch code for that bug on github or is the pre-builded APK currently the only way to solve the problem?

This is the only way for now, I plan to do an update today/tomorrow with a fix
