### ISSUE TITLE
Dark mode please

### ISSUE THREAD

**Issue by rafnov** [Fertion/QuickMDCapture#8]
It's a very interesting concept and unique for me - to add notes from notification panel. Although haven't tested enough, I notticed one thing at the very beginning - no dark mode. Could it be done? Would it be done?
There is a screenshot how it looks like when device is set to dark mode (I use dark 24/24)

![Screenshot_2024-10-24-00-15-46-70_161074dd8a59a36f2d0ca76feb852911.jpg](https://github.com/user-attachments/assets/c994f7b9-c22a-4b21-b3b8-85e064aa8340)

**Comment by Fertion** [comment]
Hi, thanks for the idea. It seems like an obvious improvement, but it didn't occur to me. I'll definitely add it.

**Comment by Fertion** [comment]
The dark theme has been added in https://github.com/Fertion/QuickMDCapture/releases/tag/1.2.1
